kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ibm-powervs-tier1
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: powervs.csi.ibm.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: tier1
allowVolumeExpansion: true
reclaimPolicy: Delete
